clear; clc; close all; 
%{
----- MAGNETORQUER SIZING MODEL -----
Written by WashU satellite MOPS to model sizing constraints of in house
magnetorquers. 
We are a team guys. 
The purpose of main.m is to input information and use wrap.m to create
a matrix of all possible designs. The results of this program is to make a 
more educated design decision for the final SCALAR magnetorquers and to 
test the manufacturing process of in house magnetorquers. 
%}

%{ 
--- TODO --- 
1. remove unnecessary wire gauges 
2. make better plots
3. add core permeability w/ some saturation 
    3a. figure out saturation 
%}

% --- Define Parameters --- % 
params.dens_cu = 8960; % kg/m^3
params.res_cu = 1.68e-8; % ohm*meter
params.dens_core = 8120; % kg/m^3
params.r_core = 0.002; % m 
params.L_core = 0.09; % m 
params.vol_core = pi*params.r_core^2*params.L_core; % m^3
params.r_max = 0.0125; % m 
params.vol_max = pi*params.r_max^2*params.L_core; % m^3
params.mass_core = params.vol_core * params.dens_core; % kg 
params.mass_max = 0.5; % kg 
params.I_battery_max = 0.5; % A 
params.V_in = 4; % V
% --- Get Magnetic Wire Data --- % 
% - Data taken from Remington Industries magnet wire - % 
T = readtable('awg.csv', 'VariableNamingRule', 'preserve'); 
AWG = T{:,'AWG'}; % gauge number
d_con_mm = T{:,'Bare Diameter (mm)'}; % diameter of bare conductor (mm) 
max_wire_current = T{:, 'Max Current (A)'}; % maximum supported wire current (A)
d_ins_mm = T{:, 'Single Build Diameter (mm)'}; % diameter including jacket (mm)
 
% --- Determine M_core --- % 
% - Equations taken from Mehrjardi et. al. - % 
mu_r = 2000; % cold-rolled 1008 low carbon steel (guess)
x = params.L_core / params.r_core; 
Nd = (4*(log(x) - 1)) / ((x)^2 - 4*log(x)); % demagnetizing factor
gain = 1 + (mu_r - 1) / (1 + (mu_r - 1)*Nd);
% --- Calls wrap() function with inputs --- % 
% Creates and populates a matrix 'D' of designs for each wire, where each 
% row is an additional wrap around the core rod. 
% The 'D' matrix is then added to a larger results matrix, 'D_results', for
% access later. 
for i = 1:height(AWG)
    d_ins = d_ins_mm(i) / 1000; % unit conversion 
    d_con = d_con_mm(i) / 1000; % unit conversion 
    awg = AWG(i); 
    % - max wire current is 80 % of what max wire can handle - % 
    I_wire_max = 0.8*max_wire_current(i); 
    N = floor(params.L_core / d_ins); % number of wire wraps 
    D = wrap(params, d_ins, d_con, N, awg, I_wire_max, gain); 
    D_results{i} = D; 
end 
% --- Write all designs to big table --- % 
AllData = []; 
for i = 1:length(D_results)
    D = D_results{i}; 
     headers = {'M_core','M_air','m_total','R_new','L_new', ...
                       'A_layer','I_new','Layer','r_outer','mass_new', ...
                       'AWG','d_ins','fail_code'};
     D = array2table(D, 'VariableNames',headers); 
     AllData = [AllData; D]; 
     D_results{i} = D; 
end 
writetable(AllData, 'D_results.csv'); 

% --- plot time --- % 

% - figure 1 - % 
% plots the outer radius of the design versus the magnetic dipole moment 
% generated by the air coil (without core gain). 
figure; hold on; grid on; 
cmap = turbo(length(D_results)); 
for i = 1:length(D_results)
    D = D_results{i};
    if ~isempty(D)
        plot(D.r_outer, D.M_air, 'LineWidth', 2, 'Color', cmap(i,:));
        awg = D.AWG(1);
        x_label = D.r_outer(end);
        y_label = D.M_air(end);

        text(x_label, y_label, sprintf('AWG %d', awg), ...
             'FontWeight','bold', 'FontSize',10, ...
             'VerticalAlignment','middle', 'HorizontalAlignment','left', ...
             'Color', cmap(i,:));
    end
end
xlabel('Outer Radius [m]');
ylabel('Magnetic Moment [A*m^2]'); 
title('Outer Radius vs. Magnetic Moment by Wire Gauge');
hold off;
clear; clc; close all; 
%{
----- MAGNETORQUER SIZING MODEL -----
Written by WashU satellite MOPS to model sizing constraints of in house
magnetorquers. 
We are a team guys. 
The purpose of main.m is to input information and use wrap.m to create
a matrix of all possible designs. The results of this program is to make a 
more educated design decision for the final SCALAR magnetorquers and to 
test the manufacturing process of in house magnetorquers. 
%}

%{ 
--- TODO --- 
1. remove unnecessary wire gauges 
2. make better plots
3. add core permeability w/ some saturation 
    3a. figure out saturation 
%}

% --- Define Parameters --- % 
params.dens_cu = 8960; % kg/m^3
params.res_cu = 1.68e-8; % ohm*meter
params.dens_core = 8120; % kg/m^3
params.r_core = 0.002; % m 
params.L_core = 0.09; % m 
params.vol_core = pi*params.r_core^2*params.L_core; % m^3
params.r_max = 0.0125; % m 
params.vol_max = pi*params.r_max^2*params.L_core; % m^3
params.mass_core = params.vol_core * params.dens_core; % kg 
params.mass_max = 0.5; % kg 
params.I_battery_max = 0.5; % A 
params.V_in = 4; % V
% --- Get Magnetic Wire Data --- % 
% - Data taken from Remington Industries magnet wire - % 
T = readtable('awg.csv', 'VariableNamingRule', 'preserve'); 
AWG = T{:,'AWG'}; % gauge number
d_con_mm = T{:,'Bare Diameter (mm)'}; % diameter of bare conductor (mm) 
max_wire_current = T{:, 'Max Current (A)'}; % maximum supported wire current (A)
d_ins_mm = T{:, 'Single Build Diameter (mm)'}; % diameter including jacket (mm)
 
% --- Determine M_core --- % 
% - Equations taken from Mehrjardi et. al. - % 
mu_r = 2000; % cold-rolled 1008 low carbon steel (guess)
x = params.L_core / params.r_core; 
Nd = (4*(log(x) - 1)) / ((x)^2 - 4*log(x)); % demagnetizing factor
gain = 1 + (mu_r - 1) / (1 + (mu_r - 1)*Nd);
% --- Calls wrap() function with inputs --- % 
% Creates and populates a matrix 'D' of designs for each wire, where each 
% row is an additional wrap around the core rod. 
% The 'D' matrix is then added to a larger results matrix, 'D_results', for
% access later. 
for i = 1:height(AWG)
    d_ins = d_ins_mm(i) / 1000; % unit conversion 
    d_con = d_con_mm(i) / 1000; % unit conversion 
    awg = AWG(i); 
    % - max wire current is 80 % of what max wire can handle - % 
    I_wire_max = 0.8*max_wire_current(i); 
    N = floor(params.L_core / d_ins); % number of wire wraps 
    D = wrap(params, d_ins, d_con, N, awg, I_wire_max, gain); 
    D_results{i} = D; 
end 
% --- Write all designs to big table --- % 
AllData = []; 
for i = 1:length(D_results)
    D = D_results{i}; 
     headers = {'M_core','M_air','m_total','R_new','L_new', ...
                       'A_layer','I_new','Layer','r_outer','mass_new', ...
                       'AWG','d_ins','fail_code'};
     D = array2table(D, 'VariableNames',headers); 
     AllData = [AllData; D]; 
     D_results{i} = D; 
end 
writetable(AllData, 'D_results.csv'); 

% --- PLOT TIME --- % 

% -- Figure 1 -- % 
% plots the outer radius of the design versus the magnetic dipole moment 
% generated by the air coil (without core gain). 
figure; hold on; grid on; 
cmap = turbo(length(D_results)); 
for i = 1:length(D_results)
    D = D_results{i};
    if ~isempty(D)
        plot(D.r_outer, D.M_air, 'LineWidth', 2, 'Color', cmap(i,:));
        awg = D.AWG(1);
        x_label = D.r_outer(end);
        y_label = D.M_air(end);

        text(x_label, y_label, sprintf('AWG %d', awg), ...
             'FontWeight','bold', 'FontSize',10, ...
             'VerticalAlignment','middle', 'HorizontalAlignment','left', ...
             'Color', cmap(i,:));
    end
end
xlabel('Outer Radius [m]');
ylabel('Magnetic Moment [A*m^2]'); 
title('Outer Radius vs. Magnetic Moment by Wire Gauge');
hold off;

% -- Figure 2 -- % 
% plots wire gauge verses magnetic dipole moment. 
figure; hold on; grid on; 
for i = 1:length(D_results)
    D= D_results{i}; 
    if ~isempty(D) 
        plot(D.AWG, D.M_air, 'LineWidth', 2);
        x_label = D.r_outer(end);
    end
end
xlabel('Magnet Wire Gauge');
ylabel('Magnetic Moment [A*m^2]'); 
title('Magnet Wire Gauge vs. Magnetic Dipole Moment');
hold off;

% -- Figure 3 -- % 
% not sure how useful this one is. 
figure; hold on; grid on; 
cmap = turbo(length(D_results)); 
for i = 1:length(D_results)
    D = D_results{i};
    if ~isempty(D)
        plot(D.r_outer, D.I_new, 'LineWidth', 2, 'Color', cmap(i,:));
        awg = D.AWG(1);
        x_label = D.r_outer(end);
        y_label = D.I_new(end);

        text(x_label, y_label, sprintf('AWG %d', awg), ...
             'FontWeight','bold', 'FontSize',10, ...
             'VerticalAlignment','middle', 'HorizontalAlignment','left', ...
             'Color', cmap(i,:));
    end
end
xlabel('Number of Wraps');
ylabel('Current [A]'); 
title('Number of Wraps versus Current Draw');
hold off;

